import React, { useState } from 'react';
import { AlertTriangle, Flag, Check } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { authedFetch } from '../utils/supabase';

/** Shown under every AI-generated result. Two store requirements in one:
 *  the medical disclaimer (App Review 1.4.1 / Play's health-app policy) and
 *  an in-app way to flag a wrong or offensive AI result (Play's
 *  AI-generated content policy) — reports land in the admin Feedback panel
 *  via /api/ai-feedback. */
export const AIResultNotice: React.FC<{ feature: 'report' | 'food' | 'plan' | 'step_review' }> = ({ feature }) => {
  const { language } = useLanguage();
  const tr = (en: string, hi: string) => (language === 'hi' ? hi : en);
  const [isReporting, setIsReporting] = useState(false);
  const [reason, setReason] = useState('');
  const [status, setStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');

  const submit = async () => {
    if (!reason.trim()) return;
    setStatus('sending');
    try {
      const res = await authedFetch('/api/ai-feedback', { method: 'POST', body: JSON.stringify({ feature, reason: reason.trim() }) });
      setStatus(res.ok ? 'sent' : 'error');
    } catch {
      setStatus('error');
    }
  };

  return (
    <div className="rounded-2xl bg-amber-50 border border-amber-200 p-3 space-y-2 text-left">
      <p className="text-[11px] leading-relaxed text-amber-900 flex gap-2">
        <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
        <span>
          {tr(
            'This result is generated by AI for general wellness information only. It is not a medical diagnosis or a substitute for advice from your doctor. Always consult a qualified doctor before changing medicines, diet or treatment.',
            'यह परिणाम AI द्वारा केवल सामान्य स्वास्थ्य जानकारी के लिए बनाया गया है। यह मेडिकल निदान या डॉक्टर की सलाह का विकल्प नहीं है। दवा, डाइट या इलाज बदलने से पहले हमेशा योग्य डॉक्टर से सलाह लें।'
          )}
        </span>
      </p>
      {status === 'sent' ? (
        <p className="text-[11px] font-bold text-emerald-700 flex items-center gap-1">
          <Check className="w-3.5 h-3.5" /> {tr('Thanks — our team will review this result.', 'धन्यवाद — हमारी टीम इस परिणाम की जाँच करेगी।')}
        </p>
      ) : isReporting ? (
        <div className="space-y-2">
          <textarea
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            rows={2}
            maxLength={1000}
            placeholder={tr('What looks wrong or inappropriate?', 'क्या गलत या अनुचित लग रहा है?')}
            className="w-full text-xs bg-white border border-amber-200 focus:border-amber-400 focus:outline-none rounded-xl px-3 py-2 text-zinc-900"
          />
          <div className="flex gap-2">
            <button type="button" onClick={() => setIsReporting(false)} className="px-3 py-1.5 rounded-xl text-[11px] font-bold text-zinc-600 bg-white border border-zinc-200 cursor-pointer">
              {tr('Cancel', 'रद्द करें')}
            </button>
            <button
              type="button"
              onClick={submit}
              disabled={status === 'sending' || !reason.trim()}
              className="px-3 py-1.5 rounded-xl text-[11px] font-black text-white bg-amber-600 hover:bg-amber-500 cursor-pointer disabled:opacity-60"
            >
              {status === 'sending' ? tr('Sending…', 'भेज रहे हैं…') : tr('Send report', 'रिपोर्ट भेजें')}
            </button>
          </div>
          {status === 'error' && (
            <p className="text-[11px] text-rose-600">{tr('Could not send. Please try again.', 'भेजा नहीं जा सका। कृपया दोबारा कोशिश करें।')}</p>
          )}
        </div>
      ) : (
        <button type="button" onClick={() => setIsReporting(true)} className="text-[11px] font-bold text-amber-800 underline flex items-center gap-1 cursor-pointer">
          <Flag className="w-3 h-3" /> {tr('Report a problem with this AI result', 'इस AI परिणाम में समस्या रिपोर्ट करें')}
        </button>
      )}
    </div>
  );
};
